### ISSUE TITLE
Time of 00 minutes will not stick after reopening the calendar

### ISSUE THREAD

**Issue by AO-TERRA** [paulhodel/jsuites#11]
When using the DateTime picker if the minutes dropdown is set to 00 it will update the appropriate text box, however, on reopening the picker the minutes dropdown will revert to the current time.

This is viewable in the "Datetime picker" example on your site [https://bossanova.uk/jsuites/date-and-datetime-picker](https://bossanova.uk/jsuites/date-and-datetime-picker)

Steps to recreate:
Pick 12:00 leaving the date as default then click update, the text box changes to 2019-08-14 12:00 as expected. 
Reopening the picker now shows 12:33 (or whatever the current minute is).
Changing the time to 12:05 and clicking update changes the text box to 2019-08-14 12:05.
Reopening the pick still shows 12:05 as expected.

**Comment by AO-TERRA** [comment]
Slight update, I've managed to find the culprit line 918 as seen below:
`var min = obj.date && obj.date[4] ? obj.date[4] : parseInt(date.getMinutes());`

I've managed to patch fix this my self in my own implementation by changing the line to:
`var min = obj.date && obj.date[4] || obj.date[4] == 0 ? obj.date[4] : parseInt(date.getMinutes());`

**Comment by paulhodel** [comment]
This has been fixed.

**Comment by perdodi** [comment]
Entering `00` as minute and/or second manually still resets to current minute and/or second.
