### ISSUE TITLE
Edit Existing Calendar Issue breaks year

### ISSUE THREAD

**Issue by wescrockett** [paulhodel/jsuites#25]
using the following for a column:
`{type: 'calendar', title: 'BLD Date',  width: 170, options: {format:'MM/DD/YYYY HH24:MI', time:true, today:1,resetButton:true,placeholder:'DD/MM/YYYY',}`

If the field was blank, pulling up the calendar works fine. If a previous value is in the cell, and the calendar is brought up, it goes to year 0002
![image](https://user-images.githubusercontent.com/4974937/75169733-e8b29400-56dd-11ea-864d-3a773e5e4f45.png)

**Comment by wescrockett** [comment]
Upon more investigation and testing, It had to do with the format I was calling the old dates into the field with.

My SQL was fetching the dates in the same format I was specifying in the JS call:
MM/dd/yyyy HH:mm

When I reformatted the SQL call to be like the examples (yyyy-MM-dd HH:mm), it started to call the year appropriately.

I suppose I would convert this from an issue to a request, then, that we could specify the datetime format

**Comment by paulhodel** [comment]
It should work with the format defined or the full format. Just make sure the format string is all capital letters.

**Comment by wescrockett** [comment]
The following shows the issue I mean:
`<html>
<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />

<div id="spreadsheet"></div>

<script>
var data = [
    ['LUX London', 'London','03/13/2020'],
];

jexcel(document.getElementById('spreadsheet'), {
    data:data,
    columns: [
        {
            type:'text',
            title:'Museum',
            width:'300',
        },
        {
            type:'dropdown',
            title:'Region',
            source:['South East','South West','North','London'],
            width:'200',
        },
        {
            type:'calendar',
            title:'Last visit',
            options: { format:'MM/DD/YYYY', time:1},
            width:'100',
        },
    ]
});
</script>
</html>`

The default date is 03/13/2020 in MM/DD/YYYY format. When you 2x click the cell to bring up the date picker, it goes to 02/0003 (in MM/YYYY format). This shows that, when inserting a data value, it must always be in YYYY-DD-MM in the data = [] array.
![image](https://user-images.githubusercontent.com/4974937/75184700-a6974b80-56f9-11ea-8903-0b527af72cb8.png)

**Comment by paulhodel** [comment]
What I meant was the copy and paste with jExcel. You can paste something to match your format and should work fine. The initialization must be with the YYYY-MM-DD or YYYY-MM-DD HH:MM:SS

**Comment by paulhodel** [comment]
I will keep that as a reference for potential improvements.

**Comment by wescrockett** [comment]
Thank you. Much appreciated. In the meantime, I will ensure I utilize it as designed.
