### ISSUE TITLE
Rollup: Parse Error: ./node_modules/jexcel/node_modules/jsuites/dist/jsuites.css:15:0

### ISSUE THREAD

**Issue by ojedabotansantiago** [paulhodel/jsuites#29]
Hy, i´m integrated jExcel in my StencilJS component, when i do a compìlation, the terminal return next error line: 

`[ ERROR ]  Rollup: Parse Error: ./node_modules/jexcel/node_modules/jsuites/dist/jsuites.css:15:0
           Unexpected token (Note that you need plugins to import files that are not JavaScript)`

i added in my file stencil.config.ts the next code to try manage a roollups: 

```
import { Config } from '@stencil/core';
import nodePolyfills from 'rollup-plugin-node-polyfills';
import { jsuites } from "jsuites";

export const config: Config = {
  namespace: 'excel-scib',
  rollupPlugins: {
    before: [
      nodePolyfills(),
    ],
    after: [
      // Plugins injected after commonjs()
      nodePolyfills()
    ]
  },
  taskQueue: 'async',
  commonjs:{
    namedExports: {
      'jsuites': ['jsuites']
    },
  },
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader'
    },
    {
      type: 'docs-readme'
    },
    {
      type: 'www',
      serviceWorker: null // disable service workers
    }
  ]
};
```

but dont work, i dont have any ideas to continue wokring with this library. 

Someone can help my plase?

Thank you.

**Comment by paulhodel** [comment]
Try that:

import * as jSuites from "jsuites";
