### ISSUE TITLE
getData([]) unable to work for me.

### ISSUE THREAD

**Issue by shroffritesh** [paulhodel/jsuites#30]
When I'm trying to feel static data in jsuites sheel. And feel data manually the in sheet then how to get cell value and cell id. Please help me to solve this.

**Comment by paulhodel** [comment]
Sorry, I am not sure if I understood your question.

**Comment by shroffritesh** [comment]
Hi Paul,
I think you did not understand my question. Not an issue, When I'm
integrating blank excel and at that time I select a single cell and add
data init. That data I want in data = [...] available in "
jexcel(document.getElementById('spreadsheet'){ data: *data*  } "  like that
every cell data i want in data = []. Hope you understood and i'm waiting
for you reply. Thank you so much.




Thanks & Regards -
Ritesh Mahesh Shroff

**Comment by paulhodel** [comment]
Sorry, still not sure. Can you see this one?
