### ISSUE TITLE
Translate calendar's action buttons

### ISSUE THREAD

**Issue by bruno-buiret** [paulhodel/jsuites#31]
Hello,

I have been using jExcel with jSuites at work to build a massive grid form. There is a column which contains a date so I used the calendar type, translated days and months but I looked into the source code and there doesn't appear to be a way to translate "Reset", "Done" and "Update".

Would it be possible to add options to translate these? 

Thanks!

**Comment by paulhodel** [comment]
You suggestion has been included and will be available in the next release during the weekend.

**Comment by bruno-buiret** [comment]
Thank you so much!
