### ISSUE TITLE
mask.run turns 0 into ""

### ISSUE THREAD

**Issue by tdamsma** [paulhodel/jsuites#33]
I see now there is a PR for this already: #17, but this is the issue

```javascript
jSuites.mask.run(1, "#.#", decimal)
// ==> 1

jSuites.mask.run(1, "0.0", decimal) 
// ==> ""
```

**Comment by tdamsma** [comment]
I would have made a PR myself of not for #34

**Comment by paulhodel** [comment]
I am working in a new version will be include all those changes soon.

**Comment by paulhodel** [comment]
It should be online next Sunday/Monday

**Comment by paulhodel** [comment]
Can you try your PR now? I have changed all end of line to \r\n
