### ISSUE TITLE
code usus mixed end of line sequences

### ISSUE THREAD

**Issue by tdamsma** [paulhodel/jsuites#34]
I get the following message when trying to make an edit for a small PR:

![image](https://user-images.githubusercontent.com/7870803/81061247-4af4f580-8ed4-11ea-952b-8b667e99acde.png)

This results in a huge diff, which makes it impossible to review PR's.

**Comment by paulhodel** [comment]
I will make sure that is clear in the next release.

**Comment by paulhodel** [comment]
It has been unified, should be OK now.
