### ISSUE TITLE
Using git tags when releasing new versions

### ISSUE THREAD

**Issue by daniel-baumann** [paulhodel/jsuites#35]
Hi,

it would be nice if you could use git tag to the corresponding tag when you release a new version, e.g.:

  git tag -a -m "Tagging version 3.1.0.' v3.1.0
  git push --tags

This would make following/tracking updates on jsuites so much easier.

Regards,
Daniel

**Comment by paulhodel** [comment]
We have improved this practise. But, if you are looking on specific version, you can look on NPM where it is better tracked.

**Comment by daniel-baumann** [comment]
Hi,

I'm not sure I understand - are you saying you're going to push tags in git (there are none yet).

Regards,
Daniel

**Comment by daniel-baumann** [comment]
It's there now, thank you!
