### ISSUE TITLE
Split components to multiple files

### ISSUE THREAD

**Issue by jimmywarting** [paulhodel/jsuites#36]
Hi, atm I'm only interested in the contextmenu plugin, i would like to only load that thing and ignore the rest

**Comment by paulhodel** [comment]
I have deploy the source code from the separeted files to the master repository. So, you have access to the plugin. Bear in mind, lot of plugins has dependencies from each other. One possible way to go is to get the jsuites.basic.js and minify, which will be around 70K with all basics of jexcel.

**Comment by jimmywarting** [comment]
grate 👍 

Just skimmed through some stuff of yours, took note of the large sha512 function you had in your helper function.

https://github.com/paulhodel/jsuites/blob/b4ac79b003cf32412936832d5b6961ab7f5e43ad/src/helpers.js#L76

A much shorter version of it that i have been using is:

```js
const text = 'An obscure body in the S-K System, your majesty. The inhabitants refer to it as the planet Earth.';
const data = new TextEncoder().encode(text);
const hash = await crypto.subtle.digest('SHA-512', data);
[...new Uint8Array(hash)].map (b => b.toString (16).padStart (2, "0")).join ("")
```

all doe the web crypto is only available in secure context...

**Comment by paulhodel** [comment]
Thanks, but we need something more compatible with old browsers since we do not require transpilation, etc.

Regards,

**Comment by jimmywarting** [comment]
just a curiosity but what is the lowest browser support that you target? ie11?
