### ISSUE TITLE
Wrong class name on context menu?

### ISSUE THREAD

**Issue by jimmywarting** [paulhodel/jsuites#38]
I tried the disabled option and tried to make it look disabled, but it still had the same color as the rest.

https://github.com/paulhodel/jsuites/blob/e5445d63065f3c8f5422dd0b57a147d11fd1eed1/dist/jsuites.js#L2169-L2171

Looking at your well written source code (since the documentation is so bad) I found out that you add the class `jcontextmenu-disabled` to disabled items, but there is no css selector that match that name.

https://github.com/paulhodel/jsuites/blob/e5445d63065f3c8f5422dd0b57a147d11fd1eed1/dist/jsuites.css#L1487-L1489

**Comment by jimmywarting** [comment]
I'm only guessing but i think it should be 
```css
.jcontextmenu .jcontextmenu-disabled a {
  color: #a1a192;
}
```

**Comment by jimmywarting** [comment]
fyi, i think you should change this too:
```diff
- .jcontextmenu > div:not(.contextmenu-line):hover {
+ .jcontextmenu > div:not(.contextmenu-line, .jcontextmenu-disabled):hover {
    background: #ebebeb;
}
```

**Comment by paulhodel** [comment]
I have fixed that.
