### ISSUE TITLE
Date to string conversion

### ISSUE THREAD

**Issue by paulbriton** [paulhodel/jsuites#39]
I've tracked down [this related issue](https://github.com/paulhodel/jexcel/issues/1031) in jExcel and I figured out that it could be solved quite easily in `jsuites.js`: 
```javascript
// Helper to convert date into string
jSuites.calendar.getDateString = function(value, format) {
    ...
    if (value) {
        var d = ''+value;
        // instead of:
        // d = d.split(' ');
        var splitStr = (d.indexOf('T') !== -1) ? 'T' : ' ';
        d = d.split(splitStr);
       ...
```

I'll be glad to do a PR but I'm also facing a mixed line endings problem like in #34.

**Comment by paulhodel** [comment]
I have unified, hopefully it is working now. Let me know if you have same problems.

**Comment by paulbriton** [comment]
Still having issue with line endings. You can check [this comparison](https://github.com/paulhodel/jsuites/compare/master...paulbriton:fix-date-to-string) with a fork.

**Comment by paulhodel** [comment]
I have change one other thing, it seems better now.

**Comment by paulbriton** [comment]
@paulhodel When do you plan to make a new release ?
