### ISSUE TITLE
Feat request: Submenu in contextmenu

### ISSUE THREAD

**Issue by jimmywarting** [paulhodel/jsuites#40]
Add support for adding submenu in contextmenu

<img src="https://i.stack.imgur.com/YoR8z.png">

**Comment by paulhodel** [comment]
This is underway. It should be available soon.

**Comment by paulhodel** [comment]
That is available in the most recent version. We are working to update the documentation now.

**Comment by paulhodel** [comment]
The documentation will be released later today, including those features.
