### ISSUE TITLE
 Multiple dropdown always show selected items

### ISSUE THREAD

**Issue by alfr3dosv** [paulhodel/jsuites#45]
I am using **remoteSearch** in the dropdown, as there are many results I would like the others selected at the bottom to always be shown

**Comment by paulhodel** [comment]
Yes, when you are filtering the selected ones are going to be always present to improve the user experience. But, I am not sure if I understood correctly. If you are experiencing any other problem, I am happy to take a look in some sort of jsfiddle or something with more information about your problem
