### ISSUE TITLE
Toolbar Suggestions

### ISSUE THREAD

**Issue by wahabmirjan** [paulhodel/jsuites#46]
Here are some suggestions for the toolbar for future reference

1. Allow state. For example, assume there is a cell is set to "bold". And assume that you click away on another cell, and then you click back on the original cell again, then the "bold" button would appear pressed when clicking back on the original cell

2. Allow custom icons in the toolbar (allow users to use their own icons).

3. Allow text instead of an icon for toolbar buttons.

**Comment by paulhodel** [comment]
It has been done.

**Comment by paulhodel** [comment]
v3.5.1

**Comment by wahabmirjan** [comment]
Thank you
