### ISSUE TITLE
autocomplete dropdown data index value

### ISSUE THREAD

**Issue by TsePakKwan** [paulhodel/jsuites#6]
Hi @paulhodel 
I have seen https://bossanova.uk/jtools/dropdown-and-autocomplete, but I can't find how to set the drop-down data index value. can you help me?

I need set drop-down data index value, like as below
`<div id="dropdown4"></div>`
`<script>
myDropdown = jApp.dropdown(document.getElementById('dropdown4'), {`
`data:[`
`            { indexValue:'13', name:'apple' },`
`            { indexValue:'15', name:'mango'},`
`],`
`    onchange:function(el,val) {`
       ` document.getElementById('log').innerHTML = 'Dropdown new value is: ' + val;`
      ` //When I selected apple this should be show 'Dropdown new value is: 13'`
   ` },`
`});`
`</script>`

**Comment by paulhodel** [comment]
Please, use: "id" instead of "indexValue"
