### ISSUE TITLE
Number-mask fails with numbers > 1000 with decimals

### ISSUE THREAD

**Issue by kabachello** [paulhodel/jsuites#8]
Hi!

I'm using jExcel and I've noticed, that numeric masks do not work correctly with 3-digit numbers with decimals. Just type "1000," in the demo on the jSuites homepage (https://bossanova.uk/jsuites/javascript-mask, first example) and it instantly changes to "10.001.000".

I'm using Chrome with German locale.

**Comment by paulhodel** [comment]
Sorry, I try "1000," and it is working fine for me. Would you like to create a jsFiddle?

**Comment by paulhodel** [comment]
It has been fixed.
