### ISSUE TITLE
Is the a way to reformat data when lazy loading autocomplete? 

### ISSUE THREAD

**Issue by kabachello** [paulhodel/jsuites#9]
I would like to use the Dropdown with lazy loading, but my data source has another data format (a JSON, but with a more complex structure). How can load data via AJAX and add some preprocessing to transform it to key-value pairs? Maybe some sort of onLoad event? OnOpen would be fine too, but then there is no setData() method to populate the Dropdown...

**Comment by paulhodel** [comment]
Yes, you have onopen. You can use that. You have setData to repopulate any dropdown.
